quarkus:
  banner:
    enabled: false
  http:
    port: 8080

"%dev":
  quarkus:
    log:
      level: DEBUG

"%test":
  quarkus:
    log:
      level: DEBUG

"%prod":
  quarkus:
    log:
      level: INFO
